### ISSUE TITLE
Could the `Hardcore Go` program be renamed?

### ISSUE THREAD

**Issue by rachelmyers** [ardanlabs/gotraining#75]
Hardcore is a word associated with porn; although I'm sure it attracts some people, it alienates others. A new name might convey the rigor and thoroughness of the program, and also avoid images of violence and misogyny.

If the organizers and community are happy with the name, I'll close this issue. But I know people in the community who would like to create a more inclusive culture, and this could be a good step in that direction.

**Comment by ardan-bkennedy** [comment]
I am not sure how to respond to this issue. We have used the name for almost a year now and not once has someone felt this way. There are workout programs, music and other things in popular culture that are considered hardcore (very intense or extreme). I believe that is the meaning people take from the name. People get excited about the class because they know it is not going to be just a basic workshop. 

With all that being said, I don't want to offend people or make them feel uncomfortable. I might ask the community to chime in so I can learn more.

**Comment by rachelmyers** [comment]
@ardan-bkennedy, Thanks for that response. I don't want this to feel like a gotcha moment, but I do want to start a conversation about it. If the community is okay with it, then I'm happy to close this out. :panda_face:

**Comment by ardan-bkennedy** [comment]
I sent out this tweet to the community to learn more.
https://twitter.com/goinggodotnet/status/675424773883748352

**Comment by tylerb** [comment]
I agree with @ardan-bkennedy on this one. "Hard-core" is a term that is associated with, and used for, many different things. Only one of those uses has to do with pornography. I think the name is fine as it is. I'm excited to take the class so I can call myself a Hardcore Gopher!

**Comment by dlsniper** [comment]
While [Wikipedia](https://en.wikipedia.org/wiki/Hardcore) and [Google](https://www.google.com/search?q=hardcore&gws_rd=ssl) seem to leave the porn part at the end if you want to really rename it to something else I guess `Diehard` would sound at least as powerful (my original thought when I've seen the title of the class was to the Hardcore Rock music genre)  (see synonyms in the screenshot below).
![snapshot166](https://cloud.githubusercontent.com/assets/607868/11756021/111bf176-a057-11e5-9a3e-a679fac79a3c.png).

On a different note, I would hope that professionals in our industry (and especially Gophers) are mature enough and have better things to think of than just porn when we see words that are often used in that domain as well. When I've seen this, it remind me of a [different issue](https://groups.google.com/forum/#!topic/golang-nuts/sN6BFoli5GE) I've read in the Go mailing list. Afterall, this one, http://www.womenwhogo.org/, seems like an even worst name if one wants to put that spin on it.

Looking forward to see what's the final decision on this.

**Comment by searls** [comment]
In an environment that's often openly hostile to non-men, I do my best to counteract that by being extra sensitive to requests like this one, even at the risk that no real negative impact was experienced. The worst case is some egos are bruised and no one is significantly benefited, which isn't so bad in the grand scheme of things.

Polling doesn't seem like the best response, because the communities already have the survivor's bias built into them—anyone who might have been impacted by the name is probably already gone.

I'm really sorry for leaving this comment without dropping in some alternative names, though. I'm not close enough to the Go community to have a bunch of "G" alliterations locked and loaded like I do with "J" and "R"

**Comment by jhersh** [comment]
The implied machismo/competitiveness/overzealousness is the first thing that comes to my mind; I find it off-putting. I think there's many more inclusive ways to convey a similar concept: "Go Fast", "GoCore", "Go:top:"...

**Comment by nz** [comment]
"Hard-Mode Go"?

**Comment by mattsiegel** [comment]
I could dig a title that had to do with tunneling :)  Dig Deeper or something like that.  (Not a fan of the machismo either.)

**Comment by ardan-bkennedy** [comment]
@rachelmyers I will be changing the name and have that ready for sometime in January. I just need to think of something that conveys the same notion of very intense or extreme.

**Comment by carlisia** [comment]
Having a busy day and kinda late to the party.

First, thank you @rachelmyers for watching out for us. An issue like this is not easy for some people to bring up, much less press on. I know it wouldn't be for me. I'm in awe of your resolution and grateful for your experience. 

For the record, in any conversation I completely 100% discount `not once has someone felt this way` type of comments. So @ardan-bkennedy, not picking on you. But I am super weary of it because it's a comment that doesn't account for the voices that turned away from commenting. Granted, there might've been none, but we don't know and it is a good starting point to take that into account.

Now, on to the issue. I had never associated the course name with porn. I was ready to accept that if people were turned off because it implied tough, I'd be fine with it. It is not an easy class, I've taken it. However, if people associate the name `hardcore` with porn, then it doesn't even matter what *I* think: as far as GoBridge goes, it is not a name we should use, especially since it affects an organization that is greater than us. And I can so easily now make that association that I'd find it hard to believe there aren't a whole lot of people who do. And one would be more than enough.

**Comment by stonean** [comment]
I've taken the class as well and never associated the name with porn or anything other the first definition: "the most active, committed, or doctrinaire members of a group or movement".

However, I agree with @carlisia , "it doesn't even matter what _I_ think". So I'll offer up an alternative: "Intense Go".

Intense is the first word that came to mind while I was taking the class and what I often use to describe it to others. I was wiped out after the first day and needed rest to mentally prepare to keep up on the next. :smile: 

Because of this, I think intense  (or a similar word as @ardan-bkennedy mentioned above) could be a better descriptor than hardcore.

**Comment by ardan-bkennedy** [comment]
@stonean I love that name  Intense Go or Go Extreme

**Comment by stonean** [comment]
@ardan-bkennedy I like Intense a bit more because I associate "intense" with mental exertion where "extreme" leans more towards physical...but that could just be me. I've been known to have _unique_ (wrong) interpretations.

**Comment by carlisia** [comment]
I love `Go Extreme`, it implies that you are *going* towards the encounter of some extreme Go knowledge, and there's a nice play on words there.

**Comment by stonean** [comment]
Twitter poll time?

**Comment by ardan-bkennedy** [comment]
Intense Go, Go Extreme, Maximum Go, Epic Go

**Comment by jlsuttles** [comment]
To offer another view point I have thought about the name "Hardcore Go" not being inclusive, but for different reasons than @rachelmyers. Although now that Rachel mentioned it, she has a great point and I doubt I will unsee it. For me hardcore is not inclusive because it refers to "the most active, committed, or doctrinaire members of a group or movement" as @dlsniper pointed out. So what about the people who are not the most active, commited, or doctrinaire, but just want to learn more? Is this training not for them? As an example, at the first Go conference I went to, after I had been programming professionally for 5 years, I was talking to someone who expressed that they loved the women in the Go community because they were such *hardcore* developers, not like those women who wear high heels and write Ruby. As a woman who has written mostly Ruby professionally and doesn't consider herself a *hardcore* programmer, I felt double excluded.

**Comment by dlsniper** [comment]
Ultimate Go(pher) ?

**Comment by nicholasa** [comment]
What about "Fanatical Go" meet ups?

**Comment by stonean** [comment]
I'll throw one more out there... thinking back through the class and the level of detail @ardan-bkennedy went into immediately, "Acute Go" came to mind.

**Comment by carlisia** [comment]
Ouch @jlsuttles.

I submit we all wear high heels at the next GopherCon.

What does one thing have to do with the other. :/

**Comment by ardan-bkennedy** [comment]
@jlsuttles Thanks for the feedback. Would a name like Ultimate Go be more appealing to you. Does it say this is more than just a basic workshop and not say any of the things you mentioned?

**Comment by carlisia** [comment]
I'm totally jk btw re: ^ above. Women should not think they have change their appearance (much less sacrifice their comfort) to prove anything to anyone.

I also no longer like Extreme Go, even thou I liked it 5 minutes ago. It brings to mind something only people with plenty of time to dedicate to it could possibly reach a level of doing well at.

I like Ultimate Go.

**Comment by nicholasa** [comment]
I retract and agree with @dlsniper. Ultimate Go.

**Comment by jlsuttles** [comment]
@ardan-bkennedy I like Ultimate Go.

**Comment by acazau** [comment]
The phrase which kept coming up during the training was "idiomatic go". This is probably the most important lesson i received from it. I learned the standards of go ......  "ANSI go"

Doesn't sound super cool but the audience should get it.

**Comment by postman0** [comment]
Wow, the thought police strikes again. I wonder if SJWs are actually the only people in whose minds "hardcore" is so rigidly tied to "porn".

**Comment by lozandier** [comment]
Since the aim of the series is to have a sophisticated understanding of Go than a basic understanding of the language—and fans of the series have concerns of the name to this extent—perhaps something along the lines of **Advanced Go** or **Well-Grounded Go**?

**Comment by LilSumac** [comment]
Go is a word associated with unrestrained movement; although I'm sure it attracts some people, it alienates paraplegics and other physically-disabled programmers. A new name might convey ease and convenience of the language, and also avoid images of ableism and physical discrimination.

**Comment by ardan-bkennedy** [comment]
After much thought we decided the keep the Hardcore branding for the classes we teach at ArdanLabs. When we offer free classes using this material through GoBridge we will refrain from using the name. 

Thank you to everyone who provided feedback and thank you to Rachel for bringing up the issue.

**Comment by kahunamoore** [comment]
"Go Spelunking!"... Also, +1 for Ultimate Go and Extreme Go would work.

**Comment by nickgeiger** [comment]
How about **Go Deeper**?

**Comment by jafd** [comment]
A patient walked in to the therapist:
Patient: "Doctor, everybody tells me I'm fixated on sex."
Doctor: "Interesting! Let's check that."
(takes out a picture with a square on it.)
Doctor: "What do you see?"
Patient: "It's a bed. People have sex on it."
(doctor takes another picture, with a triangle.)
Patient: "Doctor, I clearly see that's female pubic area."
(Another picture, with a circle.)
Patient: "Doctor, it's clearly an anus!"
The doctor sighs: "It seems that you are really fixated on sex!"
Patient: "Doctor, aren't you yourself fixated on sex?"
Doctor: "???"
Patient: "Why would you show me pictures like that, then?"

I always remember this joke when reading issues like this one.

**Comment by dlsniper** [comment]
@ardan-bkennedy I'd suggest locking the issue now that a decision was made in order to further avoid derailing of discussion and turning this into yet another ugly thread on Github. https://github.com/blog/1847-locking-conversations
